 <!-- <script>
    function addition(a,b){
        return a+b;
        try{
            if(a+b<0){
                throw new Error("some exception happened");
            }
        }catch(err){
             console.log(err);
        }
    }
    let output=addition(1,5);
    console.log(output);
</script> 

<script>
    function addition(a,b){
         return a+b;
        try{
            if(a+b<0){
                throw new Error("some thing wrong");
            }
        }catch(err){
            console.log(err);
        }
    }
    addition(4,-8);
     let output=(addition(4,-8));
     console.log(output);
</script> -->  

<!-- <script>
    function addition(a,b){
        try{
            let name = true;
            name.reverse();
        }catch(err){
            console.log(err);
        }
    }
    addition(1,-2);
    let result = 5;
    console.log(result);
</script> -->

<script>
    function addition(a,b){
        try{
            let name = true;
            name.reverse();
        }catch(err){
            console.log(err);
        }
        finally{
            console.log("yes");
        }
    }
    addition(1,-2);
    let result = 5;
    console.log(result);
</script>